- hosts: panddr
  gather_facts: yes
  user: root
  become: yes
  tasks:
  - name: add panddr user
    user: name=panddr shell=/bin/bash groups=sudo append=yes
  - authorized_key: user=panddr key=https://github.com/panddr.keys
  - user: name=kralin shell=/bin/bash groups=sudo append=yes
  - authorized_key: user=kralin key=https://github.com/kralin.keys
  - apt: name=apt-transport-https state=present
  - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  - apt_key: url=http://download.rethinkdb.com/apt/pubkey.gpg state=present
  - apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  - name: add node.js repo key
    apt_repository: repo='deb https://deb.nodesource.com/node_5.x trusty main' state=present
  - name: add rethinkdb repo key
    apt_repository: repo='deb http://download.rethinkdb.com/apt trusty main' state=present
  - name: add nginx repo key
    apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present
  - name: update apt caches
    apt: update_cache=yes
  - apt: name=git state=present
  - name: install nodejs
    apt: name=nodejs state=present
  - name: install rethinkdb
    apt: name=rethinkdb state=present
  - name: install nginx
    apt: name=nginx state=present
  - name: copy rethinkdb config file
    copy: src=default.conf dest=/etc/rethinkdb/instances.d/default.conf
    notify: init rethinkdb

  - file: path=/var/apps state=directory mode=0755
  - name: clone github repo
    git: repo=https://github.com/panddr/testapp.git dest=/var/apps/nb
  - name: npm install
    npm: path=/var/apps/nb
  - name: npm build prod
    command: /usr/bin/npm run build:prod chdir=/var/apps/nb
  - name: npm db setup
    command: /usr/bin/npm run db-setup chdir=/var/apps/nb
  - name: copy nginx config file
    copy: src=nginx_nb.conf dest=/etc/nginx/conf.d/nb.conf
    notify: restart nginx

  handlers:
  - name: init rethinkdb
    shell: /etc/init.d/rethinkdb start
  - name: restart rethinkdb
    service: name=rethinkdb state=restarted
  - name: restart nginx
    service: name=nginx state=restarted
